import icon from '../assets/icons/vuesax-bulk-clipboard-tick.svg'

export const pasos = [
  {
    icon: icon,
    estado: "Preparacion",
    numeroPaso: "Paso 1",
    informacion: "Lider de diseño e implementacion pesv",
    proceso: "REALIZADO",
  },
  {
    icon: icon,
    estado: "Preparacion",
    numeroPaso: "Paso 1",
    informacion: "Lider de diseño e implementacion pesv",
    proceso: "REALIZADO",
  },
  {
    icon: icon,
    estado: "Preparacion",
    numeroPaso: "Paso 1",
    informacion: "Lider de diseño e implementacion pesv",
    proceso: "REALIZADO",
  },
  {
    icon: icon,
    estado: "Preparacion",
    numeroPaso: "Paso 1",
    informacion: "Lider de diseño e implementacion pesv",
    proceso: "REALIZADO",
  },
  {
    icon: icon,
    estado: "Preparacion",
    numeroPaso: "Paso 1",
    informacion: "Lider de diseño e implementacion pesv",
    proceso: "REALIZADO",
  },
  ,
  {
    icon: icon,
    estado: "Preparacion",
    numeroPaso: "Paso 1",
    informacion: "Lider de diseño e implementacion pesv",
    proceso: "REALIZADO",
  },
  {
    icon: icon,
    estado: "Preparacion",
    numeroPaso: "Paso 1",
    informacion: "Lider de diseño e implementacion pesv",
    proceso: "REALIZADO",
  },
  {
    icon: icon,
    estado: "Preparacion",
    numeroPaso: "Paso 1",
    informacion: "Lider de diseño e implementacion pesv",
    proceso: "REALIZADO",
  },
  {
    icon: icon,
    estado: "Preparacion",
    numeroPaso: "Paso 1",
    informacion: "Lider de diseño e implementacion pesv",
    proceso: "REALIZADO",
  },
  {
    icon: icon,
    estado: "Preparacion",
    numeroPaso: "Paso 1",
    informacion: "Lider de diseño e implementacion pesv",
    proceso: "REALIZADO",
  },
  {
    icon: icon,
    estado: "Preparacion",
    numeroPaso: "Paso 1",
    informacion: "Lider de diseño e implementacion pesv",
    proceso: "REALIZADO",
  },
  {
    icon: icon,
    estado: "Preparacion",
    numeroPaso: "Paso 1",
    informacion: "Lider de diseño e implementacion pesv",
    proceso: "REALIZADO",
  },
  {
    icon: icon,
    estado: "Preparacion",
    numeroPaso: "Paso 1",
    informacion: "Lider de diseño e implementacion pesv",
    proceso: "REALIZADO",
  },
];